services:
  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ./django
    container_name: django
    command: >
      sh -c "until nc -z db 5432; do
             echo 'Waiting for the database...';
             sleep 1;
           done;
           python manage.py migrate &&
           daphne -b 0.0.0.0 -p 8000 pong.asgi:application"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: pong.settings
      POSTGRES_HOST: db
    volumes:
      - ./django:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
