# Generated by Django 5.1.5 on 2025-02-02 15:59

import pong.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to=pong.models.CustomUser.get_avatar_path),
        ),
    ]
