"""
Django settings for pong project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Créez les répertoires nécessaires
os.makedirs(os.path.join(MEDIA_ROOT, 'avatars'), exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cl7b%(d&25z_gcb6e+_gq4q$lh^w40wmjfbcci@%-&t8ju7nd%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['transcendence.dev', '146.19.168.104']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'pong.apps.PongConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'pong.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'pong' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pong.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.postgresql',
    'NAME': os.getenv('POSTGRES_DB', 'pong_db'),
    'USER': os.getenv('POSTGRES_USER', 'pong_user'),
    'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'securepassword'),
    'HOST': os.getenv('POSTGRES_HOST', 'db'),
    'PORT': '5432',
  }
}




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris' #?? ASK TEDDY

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "pong.authentication.CookieJWTAuthentication",
    ],
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # Par défaut 5 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Par défaut 7 jours
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

INSTALLED_APPS += [
    'channels',
]

ASGI_APPLICATION = 'pong.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

CSRF_TRUSTED_ORIGINS = ["https://transcendence.dev"]
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Configuration de l'email pour l'A2F
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '42transcendencemailer@gmail.com'
EMAIL_HOST_PASSWORD = 'nnle uutz gqpn zduu'

AUTH_USER_MODEL = 'pong.CustomUser'

# 42 OAuth Configuration
# CLIENT_ID and CLIENT_SECRET must be set in environment variables
# Example in .env file:
# OAUTH42_CLIENT_ID=your-client-id
# OAUTH42_CLIENT_SECRET=your-client-secret
# OAUTH42_REDIRECT_URI=http://localhost:8000
OAUTH42_CLIENT_ID = os.getenv('OAUTH42_CLIENT_ID')
OAUTH42_CLIENT_SECRET = os.getenv('OAUTH42_CLIENT_SECRET')

if not OAUTH42_CLIENT_ID or not OAUTH42_CLIENT_SECRET:
    if DEBUG:
        # Only show warning in development mode
        import warnings
        warnings.warn(
            "OAUTH42_CLIENT_ID or OAUTH42_CLIENT_SECRET environment variables are not set. "
            "42 OAuth authentication will not work properly."
        )

OAUTH42 = {
    'CLIENT_ID': OAUTH42_CLIENT_ID,
    'CLIENT_SECRET': OAUTH42_CLIENT_SECRET,
    'REDIRECT_URI': os.getenv('OAUTH42_REDIRECT_URI', 'https://transcendence.dev/auth/42/callback'),
    'AUTH_URL': 'https://api.intra.42.fr/oauth/authorize',
    'TOKEN_URL': 'https://api.intra.42.fr/oauth/token',
    'API_URL': 'https://api.intra.42.fr/v2',
    'SCOPE': 'public',
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'pong.blockchain': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'pong.views': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
